---
- name: Check whether Composer already exists
  stat: path=/usr/local/bin/composer
  register: composer_binary

- name: Download setup script if it doesn't exist
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: "{{ composer_checksum }}"
  when: not composer_binary.stat.exists

- name: Run setup script
  command: php /tmp/composer-setup.php -- --install-dir=/usr/local/bin/ --filename=composer creates=/usr/local/bin/composer

- name: Get rid of the downloaded setup script
  file: 
    path: /tmp/composer-setup.php
    state: absent

- name: Prepare shared directory
  file:
    path: /usr/share/composer
    state: directory

- name: Add shared vendor directory to path
  template: 
    src: composer.sh
    dest: /etc/profile.d/composer.sh
    mode: "a+x"
