---
- name: Check whether Composer already exists
  stat: 
    path: '/usr/local/bin/composer'
  register: composer_binary

- include: setup-with-wget.yml
  when: not composer_binary.stat.exists and ansible_python_version|version_compare('2.7.9', '<')
  tags: [ provision ]

- include: setup-with-get-url.yml
  when: not composer_binary.stat.exists and ansible_python_version|version_compare('2.7.9', '>=')
  tags: [ provision ]

- name: Run setup script
  command: "php {{ composer_setup_filename }} -- --install-dir=/usr/local/bin/ {{ composer_version_latest_enabled|default(True)|bool|ternary('', composer_version) }} --filename=composer creates=/usr/local/bin/composer"

- name: Get rid of the downloaded setup script
  file: 
    path: "{{ composer_setup_filename }}"
    state: absent

- name: Prepare shared directory
  file:
    path: /usr/share/composer
    state: directory

- name: Add shared vendor directory to path
  template: 
    src: composer.sh
    dest: /etc/profile.d/composer.sh
    mode: "a+x"
